version: '3.6'

services:
  app:
    build: .
    ports:
      #- 8899:8899
      - 6006:6006
    volumes:
      - ./app/:/app/
    tty: true
    container_name: wargroove-rl
    cap_add:
      - SYS_PTRACE
